# Generated by Django 4.0.6 on 2022-07-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainWeek_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datas',
        ),
    ]
